package tabelas;
// Generated 22/01/2017 13:41:04 by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import org.hibernate.annotations.LazyCollectionOption;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="Fornecedor", schema="sakila")
public class Fornecedor
{
	
	@Id
	@GeneratedValue
	private int id;
	
	@Column(name="descricao")
	private String descricao;
	
	@Column(name="nome")
	private String nome;
	
	/**mappedBy informa que o OneToMany de fornecedor e o ManyToOne de contapagar
	 *(fornecedor) se referem ao mesmo relacionamento
	**/
	@OneToMany(mappedBy="fornecedor")
	@OrderBy("valor")
	@LazyCollection(LazyCollectionOption.EXTRA)
	private List<Contapagar> contas = new ArrayList<Contapagar>();
	
	@ManyToMany
	private List<Funcionario> contatos = new ArrayList<Funcionario>();
	
	
	public Fornecedor() {
	}

	public Fornecedor(int id) {
		this.id = id;
	}

	public Fornecedor(int id, String descricao, String nome) {
		this.id = id;
		this.descricao = descricao;
		this.nome = nome;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<Contapagar> getContas() {
		return contas;
	}

	public void setContas(List<Contapagar> contas) {
		this.contas = contas;
	}

	public List<Funcionario> getContatos() {
		return contatos;
	}

	public void setContatos(List<Funcionario> contatos) {
		this.contatos = contatos;
	}

	

}
