package tabelas;
// Generated 22/01/2017 13:41:04 by Hibernate Tools 5.1.0.Alpha1

/**
 * Jornal generated by hbm2java
 */
public class Jornal implements java.io.Serializable {

	private JornalId id;
	private String nome;

	public Jornal() {
	}

	public Jornal(JornalId id) {
		this.id = id;
	}

	public Jornal(JornalId id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	public JornalId getId() {
		return this.id;
	}

	public void setId(JornalId id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
