package tabelas;
// Generated 22/01/2017 13:41:04 by Hibernate Tools 5.1.0.Alpha1

/**
 * JornalId generated by hbm2java
 */
public class JornalId implements java.io.Serializable {

	private int id;
	private int sequencial;

	public JornalId() {
	}

	public JornalId(int id, int sequencial) {
		this.id = id;
		this.sequencial = sequencial;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSequencial() {
		return this.sequencial;
	}

	public void setSequencial(int sequencial) {
		this.sequencial = sequencial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JornalId))
			return false;
		JornalId castOther = (JornalId) other;

		return (this.getId() == castOther.getId()) && (this.getSequencial() == castOther.getSequencial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getSequencial();
		return result;
	}

}
